

services:
  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - /etc/letsencrypt:/cert
    ports:
      - 80:80
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    networks:
      - nginx-proxy


networks:
  nginx-proxy:
    external: true
